version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories:
      - "/.github"
      - "/.github/actions/compile-models"
      - "/.github/actions/download-models"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/scripts"
    schedule:
      interval: "weekly"
