//
// Copyright (C) 2025 Intel Corporation.
// SPDX-License-Identifier: Apache 2.0
//

#include "vpux/compiler/dialect/VPU/IR/dialect.hpp"
#include "vpux/compiler/dialect/VPU/transforms/passes.hpp"
#include "vpux/compiler/dialect/VPU/utils/setup_pipeline_options_utils.hpp"
#include "vpux/compiler/dialect/VPU/utils/static_shape_op_utils.hpp"
#include "vpux/compiler/dialect/config/IR/ops.hpp"
#include "vpux/compiler/utils/analysis.hpp"
#include "vpux/utils/core/error.hpp"

namespace vpux::VPU {
#define GEN_PASS_DECL_SETUPENABLEEXTRASTATICSHAPEOPS
#define GEN_PASS_DEF_SETUPENABLEEXTRASTATICSHAPEOPS
#include "vpux/compiler/dialect/VPU/passes.hpp.inc"
}  // namespace vpux::VPU

using namespace vpux;

namespace {

//
// SetupEnableExtraStaticShapeOpsPass
//

class SetupEnableExtraStaticShapeOpsPass final :
        public VPU::impl::SetupEnableExtraStaticShapeOpsBase<SetupEnableExtraStaticShapeOpsPass> {
public:
    SetupEnableExtraStaticShapeOpsPass() = default;
    SetupEnableExtraStaticShapeOpsPass(const VPU::InitCompilerOptions& initCompilerOptions, Logger log)
            : _enableExtraStaticShapeOps(enableExtraStaticShapeOps) {
        Base::initLogger(log, Base::getArgumentName());
        Base::copyOptionValuesFrom(initCompilerOptions);

        initializeFromOptions();
    }

private:
    mlir::LogicalResult initializeOptions(
            StringRef options, llvm::function_ref<mlir::LogicalResult(const llvm::Twine&)> errorHandler) final;
    void safeRunOnModule() final;

private:
    // Initialize fields from pass options
    void initializeFromOptions();

private:
    bool _enableExtraStaticShapeOps = false;
    bool _allowCustomValues = false;
};

void addOption(mlir::OpBuilder optionsBuilder, config::PipelineOptionsOp pipelineOptionsOp, mlir::StringRef optionName,
               size_t optionValue, bool allowCustomValues) {
    auto hasPipelineOption = pipelineOptionsOp.lookupSymbol<config::OptionOp>(optionName) != nullptr;
    VPUX_THROW_WHEN(!allowCustomValues && hasPipelineOption,
                    "Enable Extra StaticShape ops is already defined, probably you run '--init-compiler' twice");

    if (hasPipelineOption) {
        return;
    }
    auto* ctx = optionsBuilder.getContext();
    const auto constraintAttr = mlir::StringAttr::get(ctx, optionName);
    optionsBuilder.create<config::OptionOp>(optionsBuilder.getUnknownLoc(), constraintAttr,
                                            mlir::BoolAttr::get(ctx, optionValue));
}

mlir::LogicalResult SetupEnableExtraStaticShapeOpsPass::initializeOptions(
        StringRef options, llvm::function_ref<mlir::LogicalResult(const llvm::Twine&)> errorHandler) {
    if (mlir::failed(Base::initializeOptions(options, errorHandler))) {
        return mlir::failure();
    }

    initializeFromOptions();

    return mlir::success();
}

void SetupEnableExtraStaticShapeOpsPass::initializeFromOptions() {
    if (enableExtraStaticShapeOps.hasValue()) {
        _log.trace("Overloading the default value {0} of the '_enableExtraStaticShapeOps' field to the value {1} "
                   "of the pass option 'EnableExtraStaticShapeOps' generated by MLIR",
                   _enableExtraStaticShapeOps, enableExtraStaticShapeOps);
        _enableExtraStaticShapeOps = enableExtraStaticShapeOps;
    }

    if (allowCustomValues.hasValue()) {
        _allowCustomValues = allowCustomValues.getValue();
    }
}

void SetupEnableExtraStaticShapeOpsPass::safeRunOnModule() {
    auto moduleOp = getModuleOp(getOperation());
    auto optionsBuilder = mlir::OpBuilder::atBlockBegin(moduleOp.getBody());
    auto pipelineOptionsOp = VPU::getPipelineOptionsOp(getContext(), moduleOp);
    optionsBuilder =
            mlir::OpBuilder::atBlockBegin(&pipelineOptionsOp.getOptions().front(), optionsBuilder.getListener());

    addOption(optionsBuilder, pipelineOptionsOp, VPU::ENABLE_EXTRA_STATIC_SHAPE_OPS, _enableExtraStaticShapeOps,
              _allowCustomValues);
}

}  // namespace

//
// createSetupEnableExtraStaticShapeOpsPass
//

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupEnableExtraStaticShapeOpsPass() {
    return std::make_unique<SetupEnableExtraStaticShapeOpsPass>();
}

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupEnableExtraStaticShapeOpsPass(
        const VPU::InitCompilerOptions& initCompilerOptions, Logger log) {
    return std::make_unique<SetupEnableExtraStaticShapeOpsPass>(initCompilerOptions, log);
}
