//
// Copyright (C) 2025 Intel Corporation.
// SPDX-License-Identifier: Apache-2.0
//

#include "vpux/compiler/dialect/IE/IR/ops.hpp"
#include "vpux/compiler/dialect/VPU/IR/dialect.hpp"
#include "vpux/compiler/dialect/VPU/transforms/passes.hpp"
#include "vpux/compiler/dialect/VPU/utils/cost_model/cost_model.hpp"
#include "vpux/compiler/dialect/VPU/utils/setup_pipeline_options_utils.hpp"
#include "vpux/compiler/dialect/VPU/utils/weights_table_reuse_utils.hpp"

namespace vpux::VPU {
#define GEN_PASS_DECL_SETUPWEIGHTSTABLEREUSEMODE
#define GEN_PASS_DEF_SETUPWEIGHTSTABLEREUSEMODE
#include "vpux/compiler/dialect/VPU/passes.hpp.inc"
}  // namespace vpux::VPU

using namespace vpux;

namespace {

//
// SetupWeightsTableReuseMode
//

class SetupWeightsTableReuseModePass final :
        public VPU::impl::SetupWeightsTableReuseModeBase<SetupWeightsTableReuseModePass> {
public:
    SetupWeightsTableReuseModePass() = default;
    SetupWeightsTableReuseModePass(const VPU::InitCompilerOptions& initCompilerOptions, Logger log)
            : _weightsTableReuseMode(weightsTableReuseMode) {
        Base::initLogger(log, Base::getArgumentName());
        Base::copyOptionValuesFrom(initCompilerOptions);

        initializeFromOptions();
    }

private:
    mlir::LogicalResult initializeOptions(
            StringRef options, llvm::function_ref<mlir::LogicalResult(const llvm::Twine&)> errorHandler) final;
    void safeRunOnModule() final;

private:
    // Initialize fields from pass options
    void initializeFromOptions();

private:
    vpux::WeightsTableReuseMode _weightsTableReuseMode = vpux::WeightsTableReuseMode::DISABLED;
    bool _allowCustomValues = false;
};

void addOption(mlir::OpBuilder optionsBuilder, config::PipelineOptionsOp pipelineOptionsOp, mlir::StringRef optionName,
               size_t optionValue, bool allowCustomValues) {
    auto hasPipelineOption = pipelineOptionsOp.lookupSymbol<config::OptionOp>(optionName) != nullptr;
    VPUX_THROW_WHEN(!allowCustomValues && hasPipelineOption, "{0} defined, probably you run '--init-compiler' twice",
                    optionName);

    if (hasPipelineOption) {
        return;
    }
    auto* ctx = optionsBuilder.getContext();
    const auto constraintAttr = mlir::StringAttr::get(ctx, optionName);
    optionsBuilder.create<config::OptionOp>(optionsBuilder.getUnknownLoc(), constraintAttr,
                                            mlir::IntegerAttr::get(getUInt64Type(ctx), optionValue));
}

mlir::LogicalResult SetupWeightsTableReuseModePass::initializeOptions(
        StringRef options, llvm::function_ref<mlir::LogicalResult(const llvm::Twine&)> errorHandler) {
    if (mlir::failed(Base::initializeOptions(options, errorHandler))) {
        return mlir::failure();
    }

    initializeFromOptions();

    return mlir::success();
}

void SetupWeightsTableReuseModePass::initializeFromOptions() {
    _log.trace("Overloading the default value {0} of the '_weightsTableReuseMode' field to the value {1} "
               "of the pass option 'weightsTableReuseMode' generated by MLIR",
               stringifyEnum(_weightsTableReuseMode), stringifyEnum(weightsTableReuseMode));
    _weightsTableReuseMode = weightsTableReuseMode;

    if (allowCustomValues.hasValue()) {
        _allowCustomValues = allowCustomValues.getValue();
    }
}

void SetupWeightsTableReuseModePass::safeRunOnModule() {
    auto moduleOp = getModuleOp(getOperation());
    auto optionsBuilder = mlir::OpBuilder::atBlockBegin(moduleOp.getBody());
    auto pipelineOptionsOp = VPU::getPipelineOptionsOp(getContext(), moduleOp);
    optionsBuilder =
            mlir::OpBuilder::atBlockBegin(&pipelineOptionsOp.getOptions().front(), optionsBuilder.getListener());

    addOption(optionsBuilder, pipelineOptionsOp, VPU::WEIGHTS_TABLE_REUSE_MODE,
              static_cast<size_t>(_weightsTableReuseMode), _allowCustomValues);
}

}  // namespace

//
// createSetupWeightsTableReuseModePass
//

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupWeightsTableReuseModePass() {
    return std::make_unique<SetupWeightsTableReuseModePass>();
}

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupWeightsTableReuseModePass(
        const VPU::InitCompilerOptions& initCompilerOptions, Logger log) {
    return std::make_unique<SetupWeightsTableReuseModePass>(initCompilerOptions, log);
}
