//
// Copyright (C) 2025 Intel Corporation.
// SPDX-License-Identifier: Apache 2.0
//

#include "vpux/compiler/dialect/IE/IR/ops.hpp"
#include "vpux/compiler/dialect/VPU/IR/dialect.hpp"
#include "vpux/compiler/dialect/VPU/transforms/passes.hpp"
#include "vpux/compiler/dialect/VPU/utils/cost_model/cost_model.hpp"
#include "vpux/compiler/dialect/VPU/utils/setup_pipeline_options_utils.hpp"
#include "vpux/compiler/utils/analysis.hpp"
#include "vpux/utils/core/error.hpp"

namespace vpux::VPU {
#define GEN_PASS_DECL_SETUPENABLEVPUNNPRESPLIT
#define GEN_PASS_DEF_SETUPENABLEVPUNNPRESPLIT
#include "vpux/compiler/dialect/VPU/passes.hpp.inc"
}  // namespace vpux::VPU

using namespace vpux;

namespace {

//
// SetupEnableVPUNNPreSplit
//

class SetupEnableVPUNNPreSplitPass final :
        public VPU::impl::SetupEnableVPUNNPreSplitBase<SetupEnableVPUNNPreSplitPass> {
public:
    SetupEnableVPUNNPreSplitPass() = default;
    SetupEnableVPUNNPreSplitPass(const VPU::InitCompilerOptions& initCompilerOptions, Logger log)
            : _enableVPUNNPreSplit(enableVPUNNPreSplit) {
        Base::initLogger(log, Base::getArgumentName());
        Base::copyOptionValuesFrom(initCompilerOptions);

        initializeFromOptions();
    }

private:
    mlir::LogicalResult initializeOptions(
            StringRef options, llvm::function_ref<mlir::LogicalResult(const llvm::Twine&)> errorHandler) final;
    void safeRunOnModule() final;

private:
    // Initialize fields from pass options
    void initializeFromOptions();

private:
    bool _enableVPUNNPreSplit = false;
    bool _allowCustomValues = false;
};

void addOption(mlir::OpBuilder optionsBuilder, config::PipelineOptionsOp pipelineOptionsOp, mlir::StringRef optionName,
               size_t optionValue, bool allowCustomValues) {
    auto hasPipelineOption = pipelineOptionsOp.lookupSymbol<config::OptionOp>(optionName) != nullptr;
    VPUX_THROW_WHEN(!allowCustomValues && hasPipelineOption, "{0} defined, probably you run '--init-compiler' twice",
                    optionName);

    if (hasPipelineOption) {
        return;
    }
    auto* ctx = optionsBuilder.getContext();
    const auto constraintAttr = mlir::StringAttr::get(ctx, optionName);
    optionsBuilder.create<config::OptionOp>(optionsBuilder.getUnknownLoc(), constraintAttr,
                                            mlir::BoolAttr::get(ctx, optionValue));
}

mlir::LogicalResult SetupEnableVPUNNPreSplitPass::initializeOptions(
        StringRef options, llvm::function_ref<mlir::LogicalResult(const llvm::Twine&)> errorHandler) {
    if (mlir::failed(Base::initializeOptions(options, errorHandler))) {
        return mlir::failure();
    }

    initializeFromOptions();

    return mlir::success();
}

void SetupEnableVPUNNPreSplitPass::initializeFromOptions() {
    if (enableVPUNNPreSplit.hasValue()) {
        _log.trace("Overloading the default value {0} of the '_enableVPUNNPreSplit' field to the value {1} "
                   "of the pass option 'enableVPUNNPreSplit' generated by MLIR",
                   _enableVPUNNPreSplit, enableVPUNNPreSplit);
        _enableVPUNNPreSplit = enableVPUNNPreSplit;
    }

    if (allowCustomValues.hasValue()) {
        _allowCustomValues = allowCustomValues.getValue();
    }
}

void SetupEnableVPUNNPreSplitPass::safeRunOnModule() {
    auto moduleOp = getModuleOp(getOperation());
    auto optionsBuilder = mlir::OpBuilder::atBlockBegin(moduleOp.getBody());
    auto pipelineOptionsOp = VPU::getPipelineOptionsOp(getContext(), moduleOp);
    optionsBuilder =
            mlir::OpBuilder::atBlockBegin(&pipelineOptionsOp.getOptions().front(), optionsBuilder.getListener());

    addOption(optionsBuilder, pipelineOptionsOp, VPU::VPUNN_PRE_SPLIT, _enableVPUNNPreSplit, _allowCustomValues);
}

}  // namespace

//
// createSetupEnableVPUNNPreSplitPass
//

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupEnableVPUNNPreSplitPass() {
    return std::make_unique<SetupEnableVPUNNPreSplitPass>();
}

std::unique_ptr<mlir::Pass> vpux::VPU::createSetupEnableVPUNNPreSplitPass(
        const VPU::InitCompilerOptions& initCompilerOptions, Logger log) {
    return std::make_unique<SetupEnableVPUNNPreSplitPass>(initCompilerOptions, log);
}
