//
// Copyright (C) 2025 Intel Corporation.
// SPDX-License-Identifier: Apache 2.0
//

// RUN: vpux-opt --split-input-file --init-compiler="vpu-arch=%arch%" --lower-sw-layers-to-linalg %s | FileCheck %s
// REQUIRES: arch-NPU40XX

#NCHW = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
module @SingleCosLayer {
  net.NetworkInfo entryPoint : @main inputsInfo : {
    DataInfo "input" : tensor<1x1x1x1000xf16>
  } outputsInfo : {
    DataInfo "cos" : tensor<1x1x1x1000xf16>
  }

  func.func @main(%arg0: tensor<1x1x1x1000xf16>) -> tensor<1x1x1x1000xf16> {
    %cos_res = IE.Cos(%arg0) : tensor<1x1x1x1000xf16> -> tensor<1x1x1x1000xf16>
    return %cos_res : tensor<1x1x1x1000xf16>
  }
}

// CHECK: func.func @main([[ARG0:%.+]]: tensor<1x1x1x1000xf16>) -> tensor<1x1x1x1000xf16> {
// CHECK: [[LINALG_GENERIC:%.+]] = linalg.generic
// CHECK-SAME: indexing_maps = [#NCHW, #NCHW]
// CHECK-SAME: iterator_types = ["parallel", "parallel", "parallel", "parallel"]
// CHECK-SAME: ins([[ARG0]] : tensor<1x1x1x1000xf16>)
// CHECK-SAME: outs([[ARG0]] : tensor<1x1x1x1000xf16>) {

// CHECK: ^bb0([[IN:%.+]]: f16, [[OUT:%.+]]: f16)
// CHECK: [[EXT:%.+]] = arith.extf [[IN]] : f16 to f32
// CHECK: [[COS:%.+]] = math.cos [[EXT]] : f32
// CHECK: [[TRUNC:%.+]] = arith.truncf [[COS]] : f32 to f16
// CHECK: linalg.yield [[TRUNC]] : f16
// CHECK: } -> tensor<1x1x1x1000xf16>

// CHECK: return [[LINALG_GENERIC]] : tensor<1x1x1x1000xf16>

// -----

#NCHW = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
module @SingleLogLayer {
  net.NetworkInfo entryPoint : @main inputsInfo : {
    DataInfo "input" : tensor<1x1x1x1000xf16>
  } outputsInfo : {
    DataInfo "log" : tensor<1x1x1x1000xf16>
  }

  func.func @main(%arg0: tensor<1x1x1x1000xf16>) -> tensor<1x1x1x1000xf16> {
    %log_res = IE.Log(%arg0) : tensor<1x1x1x1000xf16> -> tensor<1x1x1x1000xf16>
    return %log_res : tensor<1x1x1x1000xf16>
  }
}

// CHECK: func.func @main([[ARG0:%.+]]: tensor<1x1x1x1000xf16>) -> tensor<1x1x1x1000xf16> {
// CHECK: [[LINALG_GENERIC:%.+]] = linalg.generic
// CHECK-SAME: indexing_maps = [#NCHW, #NCHW]
// CHECK-SAME: iterator_types = ["parallel", "parallel", "parallel", "parallel"]
// CHECK-SAME: ins([[ARG0]] : tensor<1x1x1x1000xf16>)
// CHECK-SAME: outs([[ARG0]] : tensor<1x1x1x1000xf16>) {

// CHECK: ^bb0([[IN:%.+]]: f16, [[OUT:%.+]]: f16)
// CHECK: [[LOG_RES:%.+]] = math.log [[IN]] fastmath<afn> : f16
// CHECK: linalg.yield [[LOG_RES]] : f16
// CHECK: } -> tensor<1x1x1x1000xf16>

// CHECK: return [[LINALG_GENERIC]] : tensor<1x1x1x1000xf16>

// -----

#NCHW = affine_map<(d0, d1, d2, d3) -> (d0, d1, d2, d3)>
module @SingleExpLayer {
  net.NetworkInfo entryPoint : @main inputsInfo : {
    DataInfo "input" : tensor<1x1x1x1000xf16>
  } outputsInfo : {
    DataInfo "exp" : tensor<1x1x1x1000xf16>
  }

  func.func @main(%arg0: tensor<1x1x1x1000xf16>) -> tensor<1x1x1x1000xf16> {
    %exp_res = IE.Exp(%arg0) : tensor<1x1x1x1000xf16> -> tensor<1x1x1x1000xf16>
    return %exp_res : tensor<1x1x1x1000xf16>
  }
}

// CHECK: func.func @main([[ARG0:%.+]]: tensor<1x1x1x1000xf16>) -> tensor<1x1x1x1000xf16> {
// CHECK: [[LINALG_GENERIC:%.+]] = linalg.generic
// CHECK-SAME: indexing_maps = [#NCHW, #NCHW]
// CHECK-SAME: iterator_types = ["parallel", "parallel", "parallel", "parallel"]
// CHECK-SAME: ins([[ARG0]] : tensor<1x1x1x1000xf16>)
// CHECK-SAME: outs([[ARG0]] : tensor<1x1x1x1000xf16>) {

// CHECK: ^bb0([[IN:%.+]]: f16, [[OUT:%.+]]: f16)
// CHECK: [[EXP_RES:%.+]] = math.exp [[IN]] fastmath<afn> : f16
// CHECK: linalg.yield [[EXP_RES]] : f16
// CHECK: } -> tensor<1x1x1x1000xf16>

// CHECK: return [[LINALG_GENERIC]] : tensor<1x1x1x1000xf16>
