//
// Copyright (C) 2022-2025 Intel Corporation.
// SPDX-License-Identifier: Apache-2.0
//

#ifndef VPUX_COMPILER_DIALECT_VPU_OPS
#define VPUX_COMPILER_DIALECT_VPU_OPS

include "vpux/compiler/dialect/VPU/ops/activation.td"
include "vpux/compiler/dialect/VPU/ops/arithmetic.td"
include "vpux/compiler/dialect/VPU/ops/bitwise.td"
include "vpux/compiler/dialect/VPU/ops/comparison.td"
include "vpux/compiler/dialect/VPU/ops/control_flow.td"
include "vpux/compiler/dialect/VPU/ops/convolution.td"
include "vpux/compiler/dialect/VPU/ops/data_movement.td"
include "vpux/compiler/dialect/VPU/ops/data_type.td"
include "vpux/compiler/dialect/VPU/ops/dpu.td"
include "vpux/compiler/dialect/VPU/ops/eltwise.td"
include "vpux/compiler/dialect/VPU/ops/image.td"
include "vpux/compiler/dialect/VPU/ops/internal.td"
include "vpux/compiler/dialect/VPU/ops/logical.td"
include "vpux/compiler/dialect/VPU/ops/m2i.td"
include "vpux/compiler/dialect/VPU/ops/normalization.td"
include "vpux/compiler/dialect/VPU/ops/pooling.td"
include "vpux/compiler/dialect/VPU/ops/recurrent.td"
include "vpux/compiler/dialect/VPU/ops/reduce.td"
include "vpux/compiler/dialect/VPU/ops/shape_manipulation.td"
include "vpux/compiler/dialect/VPU/ops/specialized.td"


#endif
