#
# Copyright (C) 2025-2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#

set(CLANG_TIDY_PLUGIN_NAME "clang_tidy_plugin")

function(get_clang_tidy_plugin_path RETURN_PATH)
    if (NOT TARGET ${CLANG_TIDY_PLUGIN_NAME})
        message(FATAL_ERROR "No clang-tidy plugin is built. Check if build_clang_tidy_plugin has been called")
    endif()
    get_target_property(PLUGIN_PATH ${CLANG_TIDY_PLUGIN_NAME} LIBRARY_FULL_PATH)
    set(${RETURN_PATH} "${PLUGIN_PATH}" PARENT_SCOPE)
endfunction()

function(enable_clang_tidy_plugin TARGET_NAME)
    get_target_property(EXISTING_CLANG_TIDY_CALL ${TARGET_NAME} CXX_CLANG_TIDY)
    if (EXISTING_CLANG_TIDY_CALL)
        message(FATAL_ERROR "Target \"${TARGET_NAME}\" already has clang-tidy enabled")
    endif()

    get_target_property(TARGET_SOURCES ${TARGET_NAME} SOURCES)
    if (NOT TARGET_SOURCES)
        # targets without sources cannot be built
        message(FATAL_ERROR "clang-tidy plugin does not support target \"${TARGET_NAME}\" without source files")
    endif()

    find_program(CLANG_TIDY_COMMAND clang-tidy REQUIRED)

    if (EXISTS "${CMAKE_SOURCE_DIR}/.clang-tidy")
        # changes in the configuration file are not tracked
        # .clang-tidy updates won't trigger target rebuilds
        list(APPEND CLANG_TIDY_COMMAND "--config-file=${CMAKE_SOURCE_DIR}/.clang-tidy")
    endif()

    get_clang_tidy_plugin_path(CLANG_TIDY_PLUGIN_PATH)
    list(APPEND CLANG_TIDY_COMMAND "--load=${CLANG_TIDY_PLUGIN_PATH}")

    # add clang-tidy plugin as direct dependency of the sources
    # otherwise if only plugin changed, CMake won't rebuild dependent target as up-to-date
    set_source_files_properties(${TARGET_SOURCES} PROPERTIES OBJECT_DEPENDS "${CLANG_TIDY_PLUGIN_PATH}")

    set_target_properties(${TARGET_NAME} PROPERTIES CXX_CLANG_TIDY "${CLANG_TIDY_COMMAND}")
endfunction()

function(add_clang_tidy_plugin SOURCE_DIR)
    if (TARGET ${CLANG_TIDY_PLUGIN_NAME})
        message(FATAL_ERROR "${CMAKE_CURRENT_FUNCTION} has been called twice")
    endif()

    if (NOT EXISTS "${SOURCE_DIR}")
        message(FATAL_ERROR "path ${SOURCE_DIR} does not exist")
    endif()

    # use ExternalProject to build clang-tidy plugin in a separate isolated step
    # otherwise, LLVM CMake targets imported by pre-installed clang-tidy conflict
    # with LLVM CMake targets generated by LLVM fork submodule build due to name clashes
    include(ExternalProject)

    # ExternalProject is basically a black box from CMake POV
    # reconstruct the full path to the module here to be used in clang-tidy invocation
    # and LIT tests

    # assume no installation step is needed and byproducts are taken from build dir
    set(BINARY_DIR "${SOURCE_DIR}/build")
    # assume clang-tidy plugin is a shared object
    # assume clang-tidy plugin's PROJECT_NAME is the ${CLANG_TIDY_PLUGIN_NAME}
    set(LIBRARY_NAME "${CMAKE_SHARED_MODULE_PREFIX}${CLANG_TIDY_PLUGIN_NAME}${CMAKE_SHARED_MODULE_SUFFIX}")
    set(LIBRARY_FULL_PATH "${BINARY_DIR}/${LIBRARY_NAME}")

    ExternalProject_add(
        ${CLANG_TIDY_PLUGIN_NAME}
        SOURCE_DIR "${SOURCE_DIR}"
        BINARY_DIR "${BINARY_DIR}"
        # explicitly specify byproducts to make Ninja generator aware
        # of a rule that generates plugin shared object when it is used
        # as a dependency for source files of other targets
        BUILD_BYPRODUCTS "${LIBRARY_FULL_PATH}"
        # as ExternalProject is a black box, CMake won't know when to rebuild it
        # it leads to issues if source files or CMake scripts are updated
        # enforce unconditional rebuild all the time to catch any changes
        # it will not impact incremental builds since rebuild is a no-op if nothing changed
        BUILD_ALWAYS TRUE
        # by default CMake runs "install" target for installation
        # clang-tidy plugin doesn't require installation and hence doesn't define "install" target
        # explicitly disable installation step to avoid build errors
        INSTALL_COMMAND ""
    )

    set_target_properties(${CLANG_TIDY_PLUGIN_NAME} PROPERTIES LIBRARY_FULL_PATH "${LIBRARY_FULL_PATH}")
endfunction()
