name: Linux DRIVER
on:
  workflow_call:
    inputs:
      os:
        description: 'OS that is used for building in the form of "ubuntu_20_04"'
        type: string
        required: true
      build-runner:
        description: 'Machine on which the builds will run'
        type: string
        required: true

defaults:
  run:
    shell: bash

permissions: read-all

jobs:
  Dependencies:
    name: Dependencies
    runs-on: ubuntu-latest
    outputs:
      openvino_repo: ${{ steps.read_openvino_sha.outputs.ov_repo }}
      openvino_sha: ${{ steps.read_openvino_sha.outputs.ov_sha }}
      npu_repo: ${{ steps.get_npu_sha.outputs.npu_repo }}
      npu_sha: ${{ steps.get_npu_sha.outputs.npu_sha }}
      npu_tag: ${{ steps.create_npu_tag.outputs.npu_tag }}
      artifact-name: ${{ steps.artifacts.outputs.name }}
    env:
      NPU_COMPILER_REPO: ./npu_compiler
    steps:
      - name: Fetch OpenVINO config from NPU Compiler repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        timeout-minutes: 15
        with:
          sparse-checkout: |
            validation/openvino_config.json
          sparse-checkout-cone-mode: false
          path: ${{ env.NPU_COMPILER_REPO }}

      - name: Get integrated OpenVINO version
        id: read_openvino_sha
        run: |
          OV_ORG=$(jq -r 'to_entries[0].key' ${NPU_COMPILER_REPO}/validation/openvino_config.json)
          OV_SHA=$(jq -r 'to_entries[0].value' ${NPU_COMPILER_REPO}/validation/openvino_config.json)
          echo "OpenVINO orgranization = $OV_ORG"
          echo "OpenVINO commit sha = $OV_SHA"
          echo "ov_repo=$OV_ORG/openvino" >> $GITHUB_OUTPUT
          echo "ov_sha=$OV_SHA" >> $GITHUB_OUTPUT

      - name: Get NPU original fork and commit sha
        id: get_npu_sha
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "npu_repo=${{ github.event.pull_request.head.repo.full_name }}" >> $GITHUB_OUTPUT
            echo "npu_sha=${{ github.event.pull_request.head.sha }}" >> $GITHUB_OUTPUT
          else
            echo "npu_repo=${{ github.repository }}" >> $GITHUB_OUTPUT
            echo "npu_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Create NPU Compiler tag
        id: create_npu_tag
        run: |
          NPU_TAG=ci_${GITHUB_SHA:0:7}
          echo "NPU Compiler tag to be used in NPU Driver Linux build : $NPU_TAG"
          echo "npu_tag=$NPU_TAG" >> $GITHUB_OUTPUT

      - name: Configure artifacts
        id: artifacts
        run: |
          PKG_NAME=l_ov_cid_${{ inputs.os }}_npu_${{ github.sha }}
          echo "Package name : $PKG_NAME"
          echo "name=$PKG_NAME" >> $GITHUB_OUTPUT

  Build:
    name: Build
    needs: Dependencies
    runs-on: ${{ inputs.build-runner }}
    timeout-minutes: 240
    env:
      DEBIAN_FRONTEND: noninteractive
      NPU_DRIVER_REPO: ./npu_driver
      NPU_DRIVER_BUILD_DIR: ./npu_driver_build
      NPU_DRIVER_INSTALL_DIR: ./npu_driver_install
    steps:
      - name: Clone Linux NPU Driver
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        timeout-minutes: 15
        with:
          repository: intel/linux-npu-driver
          path: ${{ env.NPU_DRIVER_REPO }}
          submodules: true

      - name: System info
        uses: openvinotoolkit/openvino/.github/actions/system_info@master

      - name: Install system packages
        run: |
          sudo apt update
          sudo apt install -y build-essential git git-lfs cmake libudev-dev libboost-all-dev libssl-dev

      - name: Configure OpenVINO and NPU Compiler versions
        run: |
          sed -i "s|^set(OPENVINO_REPOSITORY .*|set(OPENVINO_REPOSITORY https://github.com/${{ needs.Dependencies.outputs.openvino_repo }})|" ${NPU_DRIVER_REPO}/compiler/compiler_source.cmake
          sed -i '/GIT_REPOSITORY/{n;s|https://github.com/openvinotoolkit/npu_plugin.git|https://github.com/${{ needs.Dependencies.outputs.npu_repo }}.git|}' ${NPU_DRIVER_REPO}/compiler/compiler_source.cmake
          sed -i "s|^set(NPU_COMPILER_TAG .*|set(NPU_COMPILER_TAG ${{ needs.Dependencies.outputs.npu_tag }})|" ${NPU_DRIVER_REPO}/compiler/compiler_source.cmake
          sed -i "s|^set(NPU_COMPILER_REVISION .*|set(NPU_COMPILER_REVISION ${{ needs.Dependencies.outputs.npu_sha }})|" ${NPU_DRIVER_REPO}/compiler/compiler_source.cmake
          sed -i "s|^set(NPU_COMPILER_OPENVINO_REVISION .*|set(NPU_COMPILER_OPENVINO_REVISION ${{ needs.Dependencies.outputs.openvino_sha }})|" ${NPU_DRIVER_REPO}/compiler/compiler_source.cmake
          cat ${NPU_DRIVER_REPO}/compiler/compiler_source.cmake

      - name: CMake configure - Linux NPU Driver
        run: |
          cmake \
            ${{ inputs.driver-cmake-options }} \
            -DENABLE_NPU_COMPILER_BUILD=ON \
            -DCMAKE_INSTALL_PREFIX=$(realpath ${NPU_DRIVER_INSTALL_DIR}) \
            -S ${NPU_DRIVER_REPO} \
            -B ${NPU_DRIVER_BUILD_DIR}

      - name: CMake build - Linux NPU Driver - deb packages
        run: |
          cmake \
            --build ${NPU_DRIVER_BUILD_DIR} \
            --parallel $(nproc) \
            --target package

      - name: Copy packages
        run: |
          mkdir -p ${NPU_DRIVER_INSTALL_DIR}/packages
          mv ${NPU_DRIVER_BUILD_DIR}/intel-{level-zero-npu,fw-npu,driver-compiler-npu}*.*deb ${NPU_DRIVER_INSTALL_DIR}/packages/
          ls -a ${NPU_DRIVER_INSTALL_DIR}
          ls -a ${NPU_DRIVER_INSTALL_DIR}/packages
