name: Linux
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - develop

concurrency:
  group: linux-${{ github.event_name }}-${{ github.ref_name }}-linux
  cancel-in-progress: true

permissions: read-all

jobs:
  Ubuntu2204:
    name: Ubuntu 22.04
    if: ${{ false }}
    uses: ./.github/workflows/job_linux.yml
    with:
      os: ubuntu_22_04
      build-runner: ubuntu-22.04-16-cores
      test-runner: ubuntu-22.04-8-cores
      build-mlir: true
      build-driver: true
      run-unit-tests: true
      run-lit-tests: true
      run-compilation-tests: true

  Ubuntu2404:
    name: Ubuntu 24.04
    uses: ./.github/workflows/job_linux.yml
    with:
      os: ubuntu_24_04
      build-runner: ubuntu-latest-32-cores
      test-runner: ubuntu-latest-8-cores
      build-cache: true
      build-cache-key-suffix: cache_${{ github.ref_name }}
      build-mlir: true
      build-driver: true
      run-unit-tests: false
      run-lit-tests: false
      run-compilation-tests: true
